name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        working-directory: bin/
        needs: |
          Imports

    - name: Install pdflatex on Linux
      run: sudo apt-get update -y && sudo apt-get install -y texlive-latex-base

    - uses: actions/checkout@v3
    
    - name: calculate-gc-count-and-generate-presentation
      run: make

    - name: gc-count
      uses: actions/upload-artifact@v3

      with:
        name: gc-content
        path: outputs/
    
    - name: presentation
      uses: actions/upload-artifact@v3

      with:
        name: presentation
        path: presentation.pdf

    - name: report
      uses: actions/upload-artifact@v3

      with:
        name: report
        path: report.pdf
